name: build garden linux container
on: push
env:
  IMAGE_NAME: gardenlinux/integration-test
jobs:
  integration_test_container:
    name: make integration test container
    runs-on: ubuntu-latest
    steps:
      - run: |
          sudo rm -rf /{usr/{local/{lib/{android,heroku},.ghcup,share/{dotnet,powershell,miniconda,swift}},share/{dotnet,miniconda,swift}},opt/{hostedtoolcache,microsoft},imagegeneration}
          sudo docker system prune -a -f
          podman system prune -a -f
          sudo podman system prune -a -f
          sudo df -h
      - uses: actions/checkout@v3

      - name: login to ghcr.io
        run: echo "${{ secrets.GITHUB_TOKEN }}" | podman login ghcr.io -u $ --password-stdin

      - name: make integration test container
        run: make --directory=container GARDENLINUX_BUILD_CRE=podman build-integration-test

      - name: upload integration test container to ghcr.io
        run: |
          echo "$IMAGE_NAME:$(bin/garden-version)"
          podman image list
          podman tag "$IMAGE_NAME:$(bin/garden-version)" "ghcr.io/gardenlinux/$IMAGE_NAME:$(bin/garden-version)"
          podman tag "$IMAGE_NAME:$(bin/garden-version)" "ghcr.io/gardenlinux/$IMAGE_NAME:$GITHUB_SHA"
          podman push "ghcr.io/gardenlinux/$IMAGE_NAME:$(bin/garden-version)"
          podman push "ghcr.io/gardenlinux/$IMAGE_NAME:$GITHUB_SHA"
