on: push
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        x: [ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, a, b, c, d, e, f ]
        y: [ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, a, b, c, d, e, f ]
    steps:
      - run: podman info
