on: push
jobs:
  images:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        arch: [ amd64, arm64 ]
        target: [ kvm, "kvm_secureboot", "kvm_secureboot_readonly", "kvm_secureboot_readonly_persistence", metal, "metal_secureboot", "metal_secureboot_readonly", "metal_secureboot_readonly_persistence", gcp, aws, "aws_secureboot", "aws_secureboot_readonly", "aws_secureboot_readonly_persistence", azure, ali, openstack, vmware, "metal_pxe", firecracker, "metal-vhost" ]
        modifier: [ "${{ inputs.default_modifier }}" ]
        include:
          - target: container
            arch: amd64
            modifier: ""
          - target: container
            arch: arm64
            modifier: ""
    steps:
      - uses: nkraetzschmar/workflow-telemetry-action@v1
        with:
          metric_frequency: 1
          proc_trace_min_duration: 10
          proc_trace_chart_max_count: 50
          comment_on_pr: false
      - uses: actions/checkout@v3
      # - name: get cname
      #   run: echo "cname=$(./build --resolve-cname "${{ matrix.target }}${{ matrix.modifier }}-${{ matrix.arch }}")" | tee -a "$GITHUB_ENV"
      - name: get cname
        run: echo "cname=$(cat /proc/sys/kernel/random/uuid)" | tee -a "$GITHUB_ENV"
      - name: create fake artifact
        run: head -c 512M /dev/urandom > "${{ env.cname }}.tar.gz"
      - uses: actions/upload-artifact@v3
        with:
          name: "${{ env.cname }}"
          path: "${{ env.cname }}.tar.gz"
