name: Build Garden Linux Vagrant Libvirt Image
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch: [ amd64, arm64 ]
    steps:
    - uses: actions/checkout@v3
    - name: Setup
      run: |
        sudo apt-get update
        sudo env DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends qemu-user-static

    - name: Build
      run: |
        ./build kvm-vagrant-${{ matrix.arch }}

    - uses: actions/upload-artifact@v3
      with:
        name: gardenlinux-vagrant-libvirt-${{ matrix.arch }}
        path: .build/kvm-vagrant-${{ matrix.arch }}*.box
